version: "2.2"
services:
  back-ecig-mock:
    image: "apozel/vapetrack-back-mock:latest"
    ports:
      - 4001:3000
    environment:
      - APP_ID=1.1
      - JWT_SECRET=envraimaintenantcestsecu
      - APP_PORT=3000
      - LOG_LEVEL=debug
      - INFLUXDB_NAME=ecig
      - INFLUXDB_USER=vapetrack_link
      - INFLUXDB_PASSWORD=secretuser
      - INFLUXDB_HOST=192.168.1.24

  iot_storage:
    image: "influxdb"
    container_name: "iot_storage"
    environment:
      - INFLUXDB_DB=ecig
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=secretadmin
      - INFLUXDB_USER=vapetrack_link
      - INFLUXDB_USER_PASSWORD=secretuser
    volumes:
      - ./data/influxdb:/var/lib/influx.db
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana
    container_name: grafana
    labels:
      - "traefik.enable=true"
      - "traefik.backend=hello"
      - "traefik.http.routers.grafana.rule=Host(`grafana.local`)"
      - "traefik.http.routers.grafana.service=grafana" # associe la route au service qu'on crée en dessous 'traefik.http.services.grafana.loadBalancer.server.port=80'
      - "traefik.http.services.grafana.loadBalancer.server.port=3000"
      - "traefik.http.middlewares.grafana.stripprefix.prefixes=/grafana"
      - "traefik.http.routers.grafana.middlewares=grafana@docker"

    ports:
      - 3001:3000
